#!/bin/bash
echo "processing $1.csv"
while read f1
do
   echo "doing: $f1" >> ingest.log
   curl -s -X POST "localhost:9200/$1/_doc" -H "Content-Type: application/json" -d "{ \"csv_line\": \"$f1\" }" >> ingest.log
   echo -e "\n\n" >> ingest.log
done < $1.csv
